In [1]:
import numpy as np

In [2]:
# using this function to generate random vector
def vectorGenerator(lower_bound=-10, 
                    upper_bound=10,
                    size=(5,1),
                    transpose=True):
    import numpy as np
    if transpose:
        return np.transpose(np.random.randint(-10, 10, (5,1)))
    return np.random.randint(-10, 10, (5,1))
vectorGenerator()

array([[-6,  4,  7, -3,  4]])

### Projection Formula
In this section, I've implemented vector projection.<br>
projecting x2 on x1 is:<br>
<h3><center>$ \overrightarrow{x_t}  = ( \frac{\overrightarrow{x_1} \cdot \overrightarrow{x_2}}{||\overrightarrow{x_1}||^2} ) * \overrightarrow{x_1}$</center></h3>
using self-generated vector generator as <b>inputs</b> of function below 
will return a vector corresponding to $\overrightarrow{x_t}$ as an <b>output</b>.

related operations to this formula such as [dot product](https://numpy.org/doc/stable/reference/generated/numpy.dot.html) and [length of a vector](https://numpy.org/doc/stable/reference/generated/numpy.dot.html) are handled by usnig numpy. 

In [3]:
def vectorProjection(vec1, onto):
    return (np.dot(a=vec1[0], b=onto[0]) / (np.linalg.norm(x=onto[0])) ** 2) * onto

In [4]:
vec1 = vectorGenerator()
vec2 = vectorGenerator()
# np.transpose to represent vector as 1 column and m rows
np.transpose(vectorProjection(vec1, vec2))

array([[ 0.60759494],
       [-0.10126582],
       [-0.60759494],
       [ 0.70886076],
       [ 0.60759494]])

# Gram schmidt
matrixGenerator function is simply generates random matrix.

In [5]:
from sympy import *
def matrixGenerator(lower=-10, upper=10, dimensions=(4, 4)):
    return np.random.randint(lower, upper, dimensions)
matrixGenerator()

array([[-10,  -2,  -9,  -4],
       [  1,   7,  -8,   9],
       [ -4,  -1,   1,  -8],
       [  8,  -2,   8,  -8]])

In [6]:
randomMatrix = matrixGenerator()
randomMatrix

array([[  4,   5,   1, -10],
       [ -4,   8,   7, -10],
       [  8,  -7,  -4,  -1],
       [ -6,   6,  -2,   1]])

lines below  will transfer matrix using reduced row echelone form implemented in sympy in order to find <b>basis</b> in original matrix.
as we now from linear algebra, leading ones in rref are basis to the matrix.

In this section, I will run my gram schmidt function on these columns in order to get orthogonal basis for the same vector space.
relatively, <b>rank</b> of the matrix is columns which are linearly independant.

<b>input</b> of my gramSchmidt functions is basis of the random generated matrix. and new orthogonal basis for the vector space is the <b>output<b/>

orthogonal basis: 
    <br>1- linearly independant
    <br>2- normalized

In [7]:
# Example: matrix =np.array([[12,5,-4,3],[-6,2,0,-10],[-4,0,8,11],[2,7,4,4]]) 
# randomMatrix= matrix
matrixObj = Matrix(randomMatrix)
rref = matrixObj.rref()
colSpace = rref[1]
rank = len(colSpace)
basis = []
for item in colSpace:
    basis.append(randomMatrix[:, item])
basis, rank

([array([ 4, -4,  8, -6]),
  array([ 5,  8, -7,  6]),
  array([ 1,  7, -4, -2]),
  array([-10, -10,  -1,   1])],
 4)

In [8]:
def gramSchmidt(matrix):
    matrix = np.array(matrix)
    if len(matrix) == 0: return
    lst = []
    r1 = basis[0]
    lst.append(r1)
    # for loop corresponding to gram schmidt formula
    for col in range(1, len(basis)):
        q = col
        for j in range(len(lst)):
            q += (q - vectorProjection(vec1=basis[col], onto=lst[j]))
        lst.append(q)
        # normalization
    for i in range(len(lst)):
        norm = np.linalg.norm(lst[i])
        lst[i] = lst[i] / norm
    return lst
gramSchmidt(matrix=basis)

[array([ 0.34815531, -0.34815531,  0.69631062, -0.52223297]),
 array([-0.20591947,  0.48047876, -0.54911858,  0.65207831]),
 array([0.25663533, 0.6330338 , 0.06843609, 0.72713342]),
 array([ 0.46468081, -0.18784969,  0.79094605, -0.35098231])]

In [9]:
np.transpose(gramSchmidt(matrix=basis))

array([[ 0.34815531, -0.20591947,  0.25663533,  0.46468081],
       [-0.34815531,  0.48047876,  0.6330338 , -0.18784969],
       [ 0.69631062, -0.54911858,  0.06843609,  0.79094605],
       [-0.52223297,  0.65207831,  0.72713342, -0.35098231]])